In [30]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [31]:
data=pd.read_csv('Churn_Modelling.csv')

In [32]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [33]:
data=data.drop(columns=['RowNumber','CustomerId','Surname'])

In [34]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [35]:
label=LabelEncoder()
data['Gender']=label.fit_transform(data['Gender'])

In [36]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [37]:
from sklearn.preprocessing import OneHotEncoder
one_hot=OneHotEncoder(sparse_output=False)
one_hot_go=one_hot.fit_transform(data[['Geography']])
geo_df=pd.DataFrame(
    one_hot_go,
    columns=one_hot.get_feature_names_out(['Geography']),
    index=data.index
)
data=pd.concat([data,geo_df],axis=1)
data.drop(columns=['Geography'],inplace=True)

In [38]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [39]:
data.isnull().sum()

CreditScore          0
Gender               0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_France     0
Geography_Germany    0
Geography_Spain      0
dtype: int64

In [40]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        10000 non-null  int64
 1   Gender             10000 non-null  int64
 2   Age                10000 non-null  int64
 3   Tenure             10000 non-null  int64
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64
 6   HasCrCard          10000 non-null  int64
 7   IsActiveMember     10000 non-null  int64
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64
 10  Geography_France   10000 non-null  float64
 11  Geography_Germany  10000 non-null  float64
 12  Geography_Spain    10000 non-null  float64
dtypes: float64(5), int64(8)
memory usage: 1015.8 KB

In [41]:
import pickle

In [42]:
with open('label.pkl','wb') as f:
    pickle.dump(label,f)

with open('one_hot.pkl','wb') as f:
    pickle.dump(one_hot,f)

In [43]:
x=data.drop(columns=['Exited'])
y=data['Exited']

In [44]:
x.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 12 columns]

In [45]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [46]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [48]:
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [49]:
import tensorflow as tf

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [ ]:
#building an ann model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
]
)

In [53]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
#compiling the model
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
los=tf.keras.losses.BinaryCrossentropy()
model.compile(
    optimizer=opt,
    loss=los,
    metrics=['accuracy']
)

In [60]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [62]:
import datetime

In [63]:
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [64]:
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [65]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [66]:
#trainig the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8369 - loss: 0.3939 - val_accuracy: 0.8550 - val_loss: 0.3551
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8558 - loss: 0.3544 - val_accuracy: 0.8530 - val_loss: 0.3635
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8540 - loss: 0.3537 - val_accuracy: 0.8630 - val_loss: 0.3452
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8620 - loss: 0.3437 - val_accuracy: 0.8590 - val_loss: 0.3399
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8601 - loss: 0.3409 - val_accuracy: 0.8525 - val_loss: 0.3537
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3378 - val_accuracy: 0.8520 - val_loss: 0.3595
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8627 - loss: 0.3370 - val_accuracy: 0.8575 - val_loss: 0.3599
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - loss: 0.3316 - val_accuracy: 0.8600 - val_loss: 0.3469
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8669 - loss: 0.3285 - val_accuracy: 0.8620 - val_loss: 0.3451
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - loss: 0.3266 - val_accuracy: 0.8540 - val_loss: 0.3524
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - loss: 0.3280 - val_accuracy: 0.8560 - val_loss: 0.3511
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.3211 - val_accuracy: 0.8600 - val_loss: 0.3495
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8709 - loss: 0.3204 - val_accuracy: 0.8560 - val_loss: 0.3543
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8685 - loss: 0.3163 - val_accuracy: 0.8600 - val_loss: 0.3536

In [67]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [72]:
!pip install TensorBoard

Requirement already satisfied: TensorBoard in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (2.5.0)
Requirement already satisfied: grpcio>=1.48.2 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (1.83.0)
Requirement already satisfied: markdown>=2.6.8 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (2.5.1)
Requirement already satisfied: packaging in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (26.2)
Requirement already satisfied: pillow in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (12.3.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (84.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from TensorBoard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from grpcio>=1.48.2->TensorBoard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\User\Desktop\ml\.venv\Lib\site-packages (from werkzeug>=1.0.1->TensorBoard) (3.0.3)

In [73]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [77]:
%tensorboard --logdir logs/fit

In [ ]:
#loading pickle file